# permissions for end users to edit registrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registration-editor-role
rules:
- apiGroups:
  - cowin.gov.io
  resources:
  - registrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cowin.gov.io
  resources:
  - registrations/status
  verbs:
  - get
