apiVersion: cowin.gov.io/v2
kind: Registration
metadata:
  name: registration-sample-v2-test
spec:
  name: "shivani2"
  verified_id: "shivani-id-2"
  registration_date: "12-13-2021"
  vaccine_name: "pfizer"
